### ISSUE TITLE
run_node 脚本建议增加对 CodeRunner 的支持

### ISSUE THREAD

**Issue by puteulanus** [xudaolong/CodeVar#1]
好吧，这个可能有点小众。。

对于安装了 CodeRunner，但是没有装 node（我连 homebrew 都没有 = =）的人，电脑上其实是有 node 的，就在 /Applications/CodeRunner.app/Contents/SharedSupport/Developer/bin 路径下。

CodeRunner 自带的集成环境：

<img width="572" alt="default" src="https://cloud.githubusercontent.com/assets/4849177/21152113/042b2a02-c1a0-11e6-8814-a65a1fa4c2d8.png">

run_node 判断 node 存在的时候，在 PATH 尾部补一个这个路径就行。

**Comment by xudaolong** [comment]
👍 谢谢你的反馈...建议你设置mac的环境变量指引指命令符号这位置...

操作如下:
http://hathaway.cc/post/69201163472/how-to-edit-your-path-environment-variables-on-mac
