### ISSUE TITLE
许多单词无法翻译及一些其他问题如下

### ISSUE THREAD

**Issue by Gentear** [xudaolong/CodeVar#15]
> 有的时候会出现如下问题，重试之后可能会得到结果

![image](https://user-images.githubusercontent.com/14846974/39026755-56031adc-4481-11e8-8c64-2a624f401e7a.png)

> 下面是一个问题，作者有时间可以debug一下

![image](https://user-images.githubusercontent.com/14846974/39026683-f9200bf4-4480-11e8-8783-04ec45f3a3d8.png)

**Comment by xudaolong** [comment]
@Gentear  要么网络不稳定 要么是那些key被注销了 最好自己弄个key自己使用哈。

**Comment by Gentear** [comment]
好的  那我自己弄几个key  谢谢作者  工具很nice 用了快一年了
