### ISSUE TITLE
如果可以加一下中间线的命名方式就好了

### ISSUE THREAD

**Issue by cgTangSong** [xudaolong/CodeVar#19]

**Comment by xudaolong** [comment]
可以的

**Comment by xudaolong** [comment]
@cgTangSong 你想要的是 'get-user-id' 这种格式？

**Comment by wu6658658** [comment]
> @cgTangSong你想要的是'get-user-id'这种格式？

是的，前端现在命名规范大多数都是中划线，确实很需要增加一个啊，感谢作者了，万分感谢，增加个 ZH 命令吧

**Comment by xudaolong** [comment]
@wu6658658  好滴呀

**Comment by xudaolong** [comment]
@wu6658658 @cgTangSong 1.3.0 版本已支持啦。
