### ISSUE TITLE
无法导入

### ISSUE THREAD

**Issue by zhanghTK** [xudaolong/CodeVar#2]
你好，我根据说明下载了CodeVar.alfredworkflow，但不能导入。
我使用的Alfred版本为Alfred 3.3 Build 801
导入其它的.alfredworkflow文件正常。

**Comment by xudaolong** [comment]
@zhanghTK  你好 请问是点击无效吗?可以自行移动过去启动么

**Comment by zhanghTK** [comment]
双击会启动Alfred，但没有导入，移动过去也不能导入，没有任何提示错误。

**Comment by zhanghTK** [comment]
今天又尝试了一下，成功导入了。我也不知道什么原因，尴尬.jpg

**Comment by xudaolong** [comment]
那还不给我个star呢 嗯哼
