### ISSUE TITLE
求教程怎么安装

### ISSUE THREAD

**Issue by lvan-zhang** [xudaolong/CodeVar#21]
作为一个新手，怎么安装啊，下载下来那个文件之后怎么安装啊，有点懵逼。。

**Comment by xudaolong** [comment]
请先安装node.js 环境， 然后双击那个包就好了啊？
你是否先安装了alfred了呀？

**Comment by lvan-zhang** [comment]
node，alfred环境有，我mac，双击CodeVar.alfredworkflow，问我要用什么app打开，我就选择alfred，然后也没反应，不知道哪的问题。。

**Comment by xudaolong** [comment]
@zhangyu187 要激活的 powerpack 才可以哦
