### ISSUE TITLE
大佬 打扰了 我这里遇到了一个问题

### ISSUE THREAD

**Issue by zhanglesheng** [xudaolong/CodeVar#23]
它显示不出来，我下载的最新版本的呢
------------
<img width="869" alt="屏幕快照 2020-01-21 上午1 03 53" src="https://user-images.githubusercontent.com/46030654/72745152-0de94980-3bea-11ea-9738-54a67080a546.png">
<img width="516" alt="屏幕快照 2020-01-21 上午1 02 15" src="https://user-images.githubusercontent.com/46030654/72745160-13df2a80-3bea-11ea-8881-d9f820dd6e2c.png">

**Comment by xudaolong** [comment]
@zhanglesheng 这个你只需要装node环境就可以了呀 

https://nodejs.org/en/download/

**Comment by zhanglesheng** [comment]
已经安装好了  谢谢您
