### ISSUE TITLE
不能识别 nvm创建的node

### ISSUE THREAD

**Issue by zangguojun** [xudaolong/CodeVar#28]
在上诉情况下，/usr/local/bin下不存在node，这个node路径能不能自定义？

**Comment by zangguojun** [comment]
暂时可以用软连接来解决这个问题  希望加一个环境变量设置功能
`ln -s /Users/#{username}/.nvm/#{nodeVersion}/bin/node /usr/local/bin/node`

**Comment by zangguojun** [comment]
暂时可以用软连接来解决这个问题  希望加一个环境变量设置功能

**Comment by zangguojun** [comment]
暂时可以用软连接来解决这个问题  希望加一个环境变量设置功能
`ln -s /Users/#{username}/.nvm/#{nodeVersion}/bin/node /usr/local/bin/node`

**Comment by xudaolong** [comment]
@zangguojun 配置下全局变量咯
