### ISSUE TITLE
翻译时间等待很久，请问这个是什么问题呢？

### ISSUE THREAD

**Issue by haoxuexiaoyao** [xudaolong/CodeVar#4]
我输入dt 后面是要翻译的词，等待几十秒，请问是什么原因呢，谢谢，你这个插件很好用，希望可以解答

**Comment by xudaolong** [comment]
这个因为里面 有道API的问题 你可以免费一个 然后替换调属于自己的... 我是手机多个API的 用的人多 压力大...有道那边要是收费的就快了 另外也要看你那边网络情况 我这边就是一两秒吧...

**Comment by xudaolong** [comment]
@haoxuexiaoyao  我这边快的话是秒翻译的  嘿嘿  你可以修改一下 dns 或者什么哒 谢谢...

**Comment by haoxuexiaoyao** [comment]
如果自己申请的话请问怎么替换呢？白天还挺快呢 晚上就很慢了，有时候几十秒等待，网速没有问题的，100MB的电信带宽一个人用

**Comment by xudaolong** [comment]
@haoxuexiaoyao 
1.http://fanyi.youdao.com/openapi?path=data-mode

2.修改 variableGlobale 的 FIXED_KEY 内容就可以了...

修改dns就可以啦 我 20mb 多人用 都没问题呢

**Comment by haoxuexiaoyao** [comment]
非常感谢你的回答，dns应该怎么修改成什么呢？

**Comment by xudaolong** [comment]
这个要看你那边的供应商了 或者网络搜搜 我用广州移动的 211.136.17.107/211.136.20.203

**Comment by haoxuexiaoyao** [comment]
明白了 谢谢
