### ISSUE TITLE
youdao  api  error

### ISSUE THREAD

**Issue by Chang-Chen** [xudaolong/CodeVar#41]
![image](https://github.com/xudaolong/CodeVar/assets/37439847/e0858a4d-5443-4e79-8ba4-5e4cf5083dde)

**Comment by DongTin** [comment]
+1 我也有同样问题

**Comment by xudaolong** [comment]
@Chang-Chen @DongTin https://github.com/xudaolong/CodeVar/pull/38#issuecomment-1643679594 参考这里
