### ISSUE TITLE
好像是翻译不出来了

### ISSUE THREAD

**Issue by JingleDingDang** [xudaolong/CodeVar#8]
今天看到了这个感觉挺好用的，但是试了一下，好像不能用了，希望作者看下原因，非常感谢！

**Comment by xudaolong** [comment]
@JingleDingDang 截图看看呀 不能用范围好广啊 对不对。

**Comment by xudaolong** [comment]
@JingleDingDang #7

**Comment by JingleDingDang** [comment]
@xudaolong 现在好了，后来发现下午有一段时间有道翻译所有网站打不开，估计是他们服务器的问题。🙂

**Comment by xudaolong** [comment]
@JingleDingDang 嗯嗯 也可以能是dns问题呢 ♪(^∇^*)
