### ISSUE TITLE
couldn't find the 'node' binary

### ISSUE THREAD

**Issue by ds462716** [xudaolong/CodeVar#9]
couldn't find the 'node' binary   
![image](https://user-images.githubusercontent.com/8003152/29265818-038eadc8-8115-11e7-9a9b-1a8b4cb82c6f.png)

**Comment by xudaolong** [comment]
@ds462716 #3 装一下node.js环境

**Comment by xudaolong** [comment]
@ds462716  ![](http://7xqvqi.com1.z0.glb.clouddn.com/15027027871653.jpg)
